default_velocity_scaling_factor: 0.10
default_acceleration_scaling_factor: 0.10

joint_limits:
  left_elbow_joint:
    has_velocity_limits: true
    max_velocity: 37.00
    has_acceleration_limits: false
    max_acceleration: 0.00
  left_shoulder_pitch_joint:
    has_velocity_limits: true
    max_velocity: 37.00
    has_acceleration_limits: false
    max_acceleration: 0.00
  left_shoulder_roll_joint:
    has_velocity_limits: true
    max_velocity: 37.00
    has_acceleration_limits: false
    max_acceleration: 0.00
  left_shoulder_yaw_joint:
    has_velocity_limits: true
    max_velocity: 37.00
    has_acceleration_limits: false
    max_acceleration: 0.00
  left_wrist_pitch_joint:
    has_velocity_limits: true
    max_velocity: 22.00
    has_acceleration_limits: false
    max_acceleration: 0.00
  left_wrist_roll_joint:
    has_velocity_limits: true
    max_velocity: 37.00
    has_acceleration_limits: false
    max_acceleration: 0.00
  left_wrist_yaw_joint:
    has_velocity_limits: true
    max_velocity: 22.00
    has_acceleration_limits: false
    max_acceleration: 0.00
  right_elbow_joint:
    has_velocity_limits: true
    max_velocity: 37.00
    has_acceleration_limits: false
    max_acceleration: 0.00
  right_shoulder_pitch_joint:
    has_velocity_limits: true
    max_velocity: 37.00
    has_acceleration_limits: false
    max_acceleration: 0.00
  right_shoulder_roll_joint:
    has_velocity_limits: true
    max_velocity: 37.00
    has_acceleration_limits: false
    max_acceleration: 0.00
  right_shoulder_yaw_joint:
    has_velocity_limits: true
    max_velocity: 37.00
    has_acceleration_limits: false
    max_acceleration: 0.00
  right_wrist_pitch_joint:
    has_velocity_limits: true
    max_velocity: 22.00
    has_acceleration_limits: false
    max_acceleration: 0.00
  right_wrist_roll_joint:
    has_velocity_limits: true
    max_velocity: 37.00
    has_acceleration_limits: false
    max_acceleration: 0.00
  right_wrist_yaw_joint:
    has_velocity_limits: true
    max_velocity: 22.00
    has_acceleration_limits: false
    max_acceleration: 0.00
  waist_pitch_joint:
    has_velocity_limits: true
    max_velocity: 37.00
    has_acceleration_limits: false
    max_acceleration: 0.00
  waist_roll_joint:
    has_velocity_limits: true
    max_velocity: 37.00
    has_acceleration_limits: false
    max_acceleration: 0.00
  waist_yaw_joint:
    has_velocity_limits: true
    max_velocity: 32.00
    has_acceleration_limits: false
    max_acceleration: 0.00
